name: CdA's website
description: Caran d'Arche is a pencil who's looking for an opportunity
twitter_username: caran
github_username: CaranDArche
author: singhprit@gmail.com

markdown: kramdown

theme: jekyll-theme-slate